# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

run:
  timeout: 5m
  go: "1.23"

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
  - durationcheck
  - errcheck
  - copyloopvar
  - forcetypeassert
  - godot
  - ineffassign
  - makezero
  - misspell
  - nilerr
  - predeclared
  - staticcheck
  - unconvert
  - unparam
  - unused
  - govet
  - cyclop
  - dupl

  settings:
    gocritic:
      disabled-checks:
      - hugeParam
    cyclop:
      max-complexity: 20
    dupl:
      threshold: 150
    godot:
      exclude:
      - "^// Test.*"
      - "^// testAcc.*"

  exclusions:
    rules:
    - path: _test\.go
      linters:
      - forcetypeassert
      - goconst
      - mnd
      - lll
      - noctx
      - gocritic
      - godot
      - unused
      - cyclop
