# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

run:
  timeout: 5m
  go: "1.24"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - forcetypeassert
        - goconst
        - mnd
        - lll
        - noctx
        - gocritic
        - godot
        - unused
        - cyclop

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
    - cyclop
    - dupl

linters-settings:
  gocritic:
    disabled-checks:
      - hugeParam
  cyclop:
    max-complexity: 20
  dupl:
    threshold: 150
  godot:
    exclude:
      - "^// Test.*"
      - "^// testAcc.*"