---
run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - forcetypeassert
        - goconst
        - gomnd
        - lll
        - noctx
        - wsl

linters-settings:
  cyclop:
    max-complexity: 15
  dupl:
    threshold: 150
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  forbidigo:
    forbid:
      - '^print.*$'
      - 'fmt\.Print.*'
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 15
  godot:
    scope: declarations
    capital: false
  gomnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/hashicorp/terraform-plugin-log/tflog).Trace
          - (github.com/hashicorp/terraform-plugin-log/tflog).Debug
          - (github.com/hashicorp/terraform-plugin-log/tflog).Info
          - (github.com/hashicorp/terraform-plugin-log/tflog).Warn
          - (github.com/hashicorp/terraform-plugin-log/tflog).Error
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false